name: Terraform Pre-Prod Plan

on:
  push:
    branches:
      - feature/branch

  pull_request:
    branches:
      - feature/branch

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_WORKING_DIR: Enviornment_Module/Enviornment/Pre_Prod
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: "0eeadee6-8ebd-4f8d-a623-b70a9252d09a"
  ARM_TENANT_ID: "d9a3ba78-3cae-4c44-bff1-be2068ede218"
  ARM_SUBSCRIPTION_ID: "1c33e61b-5e6d-4c5a-bf31-9ff658d80bc7"

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "0eeadee6-8ebd-4f8d-a623-b70a9252d09a"
          tenant-id: "d9a3ba78-3cae-4c44-bff1-be2068ede218"
          subscription-id: "1c33e61b-5e6d-4c5a-bf31-9ff658d80bc7"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan